package org.collectionspace.qa.records;

public class Citation extends Record {

    public Citation() {

        requiredMap.put("csc-placeAuthority-termDisplayName","No place like Home");

        // ----- Start of entries generated by an automated script -----
        //
        // (Note: These require review by a human.)
        // (Note: Entries for structured date fields are not yet generated.)

        fieldSelectorByLabel.put("Agent", "csc-citation-agent");
        fieldSelectorByLabel.put("Agent Information", "csc-citation-citationAgentInfoGroup");
        fieldSelectorByLabel.put("Broader Context", "csc-hierarchy-broaderContext");
        fieldSelectorByLabel.put("Broader object type", "csc-hierarchy-broaderContextType");
        fieldSelectorByLabel.put("Capture date", "csc-citationResourceIdentGroup-captureDate");
        fieldSelectorByLabel.put("Citation Information", "csc-citation-citationNameAuthorityInformation");
        fieldSelectorByLabel.put("Citation Note", "csc-citation-citationNote");
        fieldSelectorByLabel.put("Citation Record Type", "csc-citation-citationRecordType");
        fieldSelectorByLabel.put("Citation Term Group(s)", "csc-citation-citationAuthoritytation");
        fieldSelectorByLabel.put("Date", "csc-citationPublicationInfoGroup-publicationDate");
        fieldSelectorByLabel.put("Display Name", "csc-citationAuthority-termDisplayName");
        fieldSelectorByLabel.put("Edition", "csc-citation-edition");
        fieldSelectorByLabel.put("Equivalent Context", "csc-hierarchy-equivalentContexts");
        fieldSelectorByLabel.put("Formatted Display Name", "csc-citationAuthority-termFormattedDisplayName");
        fieldSelectorByLabel.put("Full Citation", "csc-citationAuthority-termFullCitation");
        fieldSelectorByLabel.put("Issue", "csc-citationAuthority-termIssue");
        fieldSelectorByLabel.put("Language", "csc-citationAuthority-termLanguage");
        fieldSelectorByLabel.put("Narrower Context", "csc-hierarchy-narrowerContext");
        fieldSelectorByLabel.put("Note", "csc-citation-note");
        fieldSelectorByLabel.put("Object component type", "csc-hierarchy-narrowerContextType");
        fieldSelectorByLabel.put("Page(s)", "csc-citation-pages");
        fieldSelectorByLabel.put("Place", "csc-citation-publicationPlace");
        fieldSelectorByLabel.put("Pref for Lang", "csc-citationAuthority-termPrefForLang");
        fieldSelectorByLabel.put("Publication Information", "csc-citation-citationPublicationInfoGroup");
        fieldSelectorByLabel.put("Publisher", "csc-citation-publisher");
        fieldSelectorByLabel.put("Qualifier", "csc-citationAuthority-termQualifier");
        fieldSelectorByLabel.put("Related Term", "csc-hierarchy-relatedTerms");
        fieldSelectorByLabel.put("Related term", "csc-citation-relatedTerm");
        fieldSelectorByLabel.put("Related terms", "csc-citation-citationRelatedTermsGroup");
        fieldSelectorByLabel.put("Resource Identifier", "csc-citation-resourceIdent");
        fieldSelectorByLabel.put("Resource Identifiers", "csc-citation-citationResourceIdentGroup");
        fieldSelectorByLabel.put("Role", "csc-citation-role");
        fieldSelectorByLabel.put("Section title", "csc-citationAuthority-termSectionTitle");
        fieldSelectorByLabel.put("Source", "csc-citationAuthority-termSource");
        fieldSelectorByLabel.put("Source Detail", "csc-citationAuthority-termSourceDetail");
        fieldSelectorByLabel.put("Source ID", "csc-citationAuthority-termSourceID");
        fieldSelectorByLabel.put("Source Note", "csc-citationAuthority-termSourceNote");
        fieldSelectorByLabel.put("Status", "csc-citationAuthority-termStatus");
        fieldSelectorByLabel.put("Subtitle", "csc-citationAuthority-termSubTitle");
        fieldSelectorByLabel.put("Term", "csc-citationAuthority-termName");
        fieldSelectorByLabel.put("Term Flag", "csc-citationAuthority-termFlag");
        fieldSelectorByLabel.put("Term Type", "csc-citationAuthority-termType");
        fieldSelectorByLabel.put("Title", "csc-citationAuthority-termTitle");
        fieldSelectorByLabel.put("Type", "csc-citation-relationType");
        fieldSelectorByLabel.put("Type", "csc-citation-type");
        fieldSelectorByLabel.put("Volume", "csc-citationAuthority-termVolume");

        // Entries above with duplicate text labels, to be checked by a human.
        //
        // Some may represent labels for headers above repeatable fields/groups.
        // Duplicate text label: Type (appears 2 times)

        // Messagekeys in the 'uispec' file not matched by text labels
        // in the message bundles file (e.g. 'core-messages.properties').
        //
        // Some of these may be record metadata that is never displayed
        // in the UI. If so, they can be added to the script's stoplist.
        //
        // In other instances, these may represent messagekeys for section
        // headers in the record, rather than for fields.
        //
        // Finally, these may represent sub-records (e.g. Contact in
        // Person and Organization) or other sub-data structures.
        //
        // Not found: text label for message key 'citation-citationRecordTypesLabel'
        // Not found: text label for message key 'hierarchy-domaindataLabel'
        // Not found: text label for message key 'hierarchy-equivalentContextLabel'
        // Not found: text label for message key 'hierarchy-equivalentInformationLabel'
        // Not found: text label for message key 'hierarchy-hierarchyInformationLabel'
        // Not found: text label for message key 'hierarchy-narrowerContextsLabel'
        // Not found: text label for message key 'hierarchy-relatedTermLabel'
        // Not found: text label for message key 'citationAuthority-citationTermGroupLabel'
        // Not found: text label for message key 'citationAuthority-termInformationLabel'

        // ----- End of entries generated by an automated script -----

    }
}
