package org.collectionspace.qa.records;

public class Concept extends Record {

    public Concept() {

        requiredMap.put("csc-ConceptAuthority-termDisplayName", "A very concepty concept");

        // ----- Start of entries generated by an automated script -----
        //
        // (Note: These require review by a human.)
        // (Note: Entries for structured date fields are not yet generated.)

        fieldSelectorByLabel.put("Additional Source", "csc-concept-additionalSourceDetail");
        fieldSelectorByLabel.put("Additional Source Detail", "csc-concept-additionalSourceID");
        fieldSelectorByLabel.put("Additional Source Note", "csc-concept-additionalSourceNote");
        fieldSelectorByLabel.put("Additional Source Unique ID", "csc-concept-additionalSource");
        fieldSelectorByLabel.put("Additional Sources", "csc-concept-additionalSourceGroup");
        fieldSelectorByLabel.put("Broader Context", "csc-hierarchy-broaderContext");
        fieldSelectorByLabel.put("Broader object type", "csc-hierarchy-broaderContextType");
        fieldSelectorByLabel.put("Citation", "csc-concept-citationSource");
        fieldSelectorByLabel.put("Citation Source Detail", "csc-concept-citationSourceDetail");
        fieldSelectorByLabel.put("Citations", "csc-concept-citationGroup");
        fieldSelectorByLabel.put("Concept Record Type", "csc-concept-conceptRecordType");
        fieldSelectorByLabel.put("Concept Term Group(s)", "csc-concept-preferredConcept");
        fieldSelectorByLabel.put("Display Name", "csc-conceptAuthority-termDisplayName");
        fieldSelectorByLabel.put("Equivalent Context", "csc-hierarchy-equivalentContexts");
        fieldSelectorByLabel.put("Formatted Display Name", "csc-conceptAuthority-termFormattedDisplayName");
        fieldSelectorByLabel.put("Historical Flag", "csc-conceptAuthority-historicalStatus");
        fieldSelectorByLabel.put("Language", "csc-conceptAuthority-termLanguage");
        fieldSelectorByLabel.put("Narrower Context", "csc-hierarchy-narrowerContext");
        fieldSelectorByLabel.put("Object component type", "csc-hierarchy-narrowerContextType");
        fieldSelectorByLabel.put("Pref for Lang", "csc-conceptAuthority-termPrefForLang");
        fieldSelectorByLabel.put("Qualifier", "csc-conceptAuthority-termQualifier");
        fieldSelectorByLabel.put("Related Term", "csc-hierarchy-relatedTerms");
        fieldSelectorByLabel.put("Scope Note", "csc-concept-scopeNote");
        fieldSelectorByLabel.put("Scope Note Source", "csc-concept-scopeNoteSource");
        fieldSelectorByLabel.put("Scope Note Source Detail", "csc-concept-scopeNoteSourceDetail");
        fieldSelectorByLabel.put("Source", "csc-conceptAuthority-termSource");
        fieldSelectorByLabel.put("Source Detail", "csc-conceptAuthority-termSourceDetail");
        fieldSelectorByLabel.put("Source ID", "csc-conceptAuthority-termSourceID");
        fieldSelectorByLabel.put("Source Note", "csc-conceptAuthority-termSourceNote");
        fieldSelectorByLabel.put("Status", "csc-conceptAuthority-termStatus");
        fieldSelectorByLabel.put("Term", "csc-conceptAuthority-termName");
        fieldSelectorByLabel.put("Term Flag", "csc-conceptAuthority-termFlag");
        fieldSelectorByLabel.put("Term Type", "csc-conceptAuthority-termType");

        // Entries above with duplicate text labels, to be checked by a human.
        //
        // Some may represent labels for headers above repeatable fields/groups.
        // (No duplicate entries generated here by script)

        // Messagekeys in the 'uispec' file not matched by text labels
        // in the message bundles file (e.g. 'core-messages.properties').
        //
        // Some of these may be record metadata that is never displayed
        // in the UI. If so, they can be added to the script's stoplist.
        //
        // In other instances, these may represent messagekeys for section
        // headers in the record, rather than for fields.
        //
        // Finally, these may represent sub-records (e.g. Contact in
        // Person and Organization) or other sub-data structures.
        //
        // Not found: text label for message key 'concept-conceptAuthorityInformationLabel'
        // Not found: text label for message key 'concept-conceptRecordTypesLabel'
        // Not found: text label for message key 'concept-descriptionLabel'
        // Not found: text label for message key 'hierarchy-domaindataLabel'
        // Not found: text label for message key 'hierarchy-equivalentContextLabel'
        // Not found: text label for message key 'hierarchy-equivalentInformationLabel'
        // Not found: text label for message key 'hierarchy-hierarchyInformationLabel'
        // Not found: text label for message key 'hierarchy-narrowerContextsLabel'
        // Not found: text label for message key 'hierarchy-relatedTermLabel'
        // Not found: text label for message key 'conceptAuthority-conceptTermGroupLabel'
        // Not found: text label for message key 'conceptAuthority-termInformationLabel'

        // ----- End of entries generated by an automated script -----    
      
      }
}
