package org.collectionspace.qa.records;

public class ConditionCheck extends Record {

    public ConditionCheck() {


        fieldSelectorByLabel.put("Earliest Next Condition Check/Assessment Date",  "csc-conditioncheck-nextConditionCheckDateStart");
        fieldSelectorByLabel.put("Latest Next Condition Check/Assessment Date",    "csc-conditioncheck-nextConditionCheckDateEnd");
        fieldSelectorByLabel.put("Earliest Condition Check/Assessment Date",       "csc-conditioncheck-conditionCheckAssessmentDateStart");
        fieldSelectorByLabel.put("Latest Condition Check/Assessment Date",         "csc-conditioncheck-conditionCheckAssessmentDateEnd");


        dropDownMap.put("Condition",                                               "csc-conditioncheck-condition");
        dropDownMap.put("Conservation Treatment Priority",                         "csc-conditioncheck-conservationTreatmentPriority");
        dropDownMap.put("Object Audit Category",                                   "csc-conditioncheck-objectAuditCategory");

      // ----- Start of entries generated by an automated script -----
      //
      // (Note: These require review by a human.)
      // (Note: Entries for structured date fields are not yet generated.)

      fieldSelectorByLabel.put("Completeness", "csc-conditioncheck-completeness");
      fieldSelectorByLabel.put("Completeness", "csc-conditioncheck-completenessGroup");
      fieldSelectorByLabel.put("Completeness Date", "csc-conditioncheck-completenessDate");
      fieldSelectorByLabel.put("Completeness Note", "csc-conditioncheck-completenessNote");
      fieldSelectorByLabel.put("Condition", "csc-conditioncheck-condition");
      fieldSelectorByLabel.put("Condition", "csc-conditioncheck-conditionCheckGroup");
      fieldSelectorByLabel.put("Condition Check/Assessment Date", "csc-conditioncheck-conditionCheckAssessmentDate");
      fieldSelectorByLabel.put("Condition Check/Assessment Method", "csc-conditioncheck-conditionCheckMethod");
      fieldSelectorByLabel.put("Condition Check/Assessment Note", "csc-conditioncheck-conditionCheckNote");
      fieldSelectorByLabel.put("Condition Check/Assessment Reason", "csc-conditioncheck-conditionCheckReason");
      fieldSelectorByLabel.put("Condition Check/Assessment Reference Number", "csc-conditioncheck-numberPatternChooser-reference-number");
      fieldSelectorByLabel.put("Condition Check/Technical Assessment Information", "csc-conditioncheck-conditionCheckInformation");
      fieldSelectorByLabel.put("Condition Checker/Assessor", "csc-conditioncheck-conditionChecker");
      fieldSelectorByLabel.put("Condition Date", "csc-conditioncheck-conditionDate");
      fieldSelectorByLabel.put("Condition Note", "csc-conditioncheck-conditionNote");
      fieldSelectorByLabel.put("Conservation Treatment Priority", "csc-conditioncheck-conservationTreatmentPriority");
      fieldSelectorByLabel.put("Display Recommendations", "csc-conditioncheck-displayRecommendations");
      fieldSelectorByLabel.put("Environmental Condition Date", "csc-conditioncheck-envConditionNoteDate");
      fieldSelectorByLabel.put("Environmental Condition Note", "csc-conditioncheck-envConditionNote");
      fieldSelectorByLabel.put("Environmental Condition Note", "csc-conditioncheck-envConditionNoteGroup");
      fieldSelectorByLabel.put("Environmental Recommendations", "csc-conditioncheck-envRecommendations");
      fieldSelectorByLabel.put("Handling Recommendations", "csc-conditioncheck-handlingRecommendations");
      fieldSelectorByLabel.put("Hazard", "csc-conditioncheck-hazard");
      fieldSelectorByLabel.put("Hazard", "csc-conditioncheck-hazardGroup");
      fieldSelectorByLabel.put("Hazard Date", "csc-conditioncheck-hazardDate");
      fieldSelectorByLabel.put("Hazard Note", "csc-conditioncheck-hazardNote");
      fieldSelectorByLabel.put("Legal/License Requirements", "csc-conditioncheck-legalRequirements");
      fieldSelectorByLabel.put("Legal/License Requirements Held", "csc-conditioncheck-legalReqsHeld");
      fieldSelectorByLabel.put("Legal/License Requirements Held", "csc-conditioncheck-legalReqsHeldGroup");
      fieldSelectorByLabel.put("Legal/License Requirements Held Begin Date", "csc-conditioncheck-legalReqsHeldBeginDate");
      fieldSelectorByLabel.put("Legal/License Requirements Held End Date", "csc-conditioncheck-legalReqsHeldEndDate");
      fieldSelectorByLabel.put("Legal/License Requirements Held Number", "csc-conditioncheck-legalReqsHeldNumber");
      fieldSelectorByLabel.put("Legal/License Requirements Held Renew Date", "csc-conditioncheck-legalReqsHeldRenewDate");
      fieldSelectorByLabel.put("Next Condition Check/Assessment Date", "csc-conditioncheck-nextConditionCheckDate");
      fieldSelectorByLabel.put("Object Audit Category", "csc-conditioncheck-objectAuditCategory");
      fieldSelectorByLabel.put("Object Condition and Technical Assessment Information", "csc-conditioncheck-objectConditionInformation");
      fieldSelectorByLabel.put("Object Requirement Information", "csc-conditioncheck-objectRequirementInformation");
      fieldSelectorByLabel.put("Packing Recommendations", "csc-conditioncheck-packingRecommendations");
      fieldSelectorByLabel.put("Salvage Priority Code", "csc-conditioncheck-salvagePriorityCode");
      fieldSelectorByLabel.put("Salvage Priority Code", "csc-conditioncheck-salvagePriorityCodeGroup");
      fieldSelectorByLabel.put("Salvage Priority Code Date", "csc-conditioncheck-salvagePriorityCodeDate");
      fieldSelectorByLabel.put("Security Recommendations", "csc-conditioncheck-securityRecommendations");
      fieldSelectorByLabel.put("Special Requirements", "csc-conditioncheck-specialRequirements");
      fieldSelectorByLabel.put("Storage Requirements", "csc-conditioncheck-storageRequirements");
      fieldSelectorByLabel.put("Technical Assessment", "csc-conditioncheck-techAssessment");
      fieldSelectorByLabel.put("Technical Assessment", "csc-conditioncheck-techAssessmentGroup");
      fieldSelectorByLabel.put("Technical Assessment Date", "csc-conditioncheck-techAssessmentDate");

      // Entries above with duplicate text labels, to be checked by a human.
      //
      // Some may represent labels for headers above repeatable fields/groups.
      // Duplicate text label: Completeness (appears 2 times)
      // Duplicate text label: Condition (appears 2 times)
      // Duplicate text label: Environmental Condition Note (appears 2 times)
      // Duplicate text label: Hazard (appears 2 times)
      // Duplicate text label: Legal/License Requirements Held (appears 2 times)
      // Duplicate text label: Salvage Priority Code (appears 2 times)
      // Duplicate text label: Technical Assessment (appears 2 times)

      // ----- End of entries generated by an automated script -----

    }
}
