package org.collectionspace.qa.records;

public class Exhibition extends Record {

    public Exhibition(){
        fieldSelectorByLabel.put("Earliest Venue Opening Date",     "csc-exhibition-venueOpeningDateStart");
        fieldSelectorByLabel.put("Latest Venue Opening Date",       "csc-exhibition-venueOpeningDateEnd");
        fieldSelectorByLabel.put("Venue Opening Date",              "csc-exhibition-venueOpeningDate");
        fieldSelectorByLabel.put("Record last modified by",         "csc-exhibition-updatedBy");

        dropDownMap.put("Exhibition Type", "csc-exhibition-type");

        xpathMap.put("Sponsor",     "//*[@id=\"primaryTab\"]/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[2]/div/ul/li/input[3]");
        xpathMap.put("Sponsor Search",            "//*[@id=\"all-content\"]/div/div[1]/div/div/div/div[2]/div[4]/div/div/div/div/div[4]/div[2]/div/ul/li/input[3]");
        xpathMap.put("Venue",       "//*[@id=\"repeat::\"]/td[2]/input[2]");


      // ----- Start of entries generated by an automated script -----
      //
      // (Note: These require review by a human.)
      // (Note: Entries for structured date fields are not yet generated.)

      fieldSelectorByLabel.put("ADD_ME", "csc-workingGroup-exhibitionPersonGroup");
      fieldSelectorByLabel.put("Attendance", "csc-exhibition-venueAttendance");
      fieldSelectorByLabel.put("Bibliographic References", "csc-exhibition-exhibitionReferenceGroup");
      fieldSelectorByLabel.put("Boilerplate Text", "csc-exhibition-boilerplateText");
      fieldSelectorByLabel.put("Case", "csc-exhibition-exhibitionObjectCase");
      fieldSelectorByLabel.put("Closing Date", "csc-exhibition-venueClosingDate");
      fieldSelectorByLabel.put("Cons. Check", "csc-exhibition-exhibitionObjectConsCheckDate");
      fieldSelectorByLabel.put("Cons. Treatment", "csc-exhibition-exhibitionObjectConsTreatment");
      fieldSelectorByLabel.put("Curatorial Notes", "csc-exhibition-curatorialNote");
      fieldSelectorByLabel.put("End Date", "csc-galleryRotationGroup-galleryRotationEndDateGroup");
      fieldSelectorByLabel.put("Exhibited Object Information", "csc-exhibition-exhibitionObjectInformation");
      fieldSelectorByLabel.put("Exhibition Information", "csc-exhibition-exhibitionInformation");
      fieldSelectorByLabel.put("Exhibition Number", "csc-exhibition-exhibitionNumber");
      fieldSelectorByLabel.put("Exhibition Planning Information", "csc-exhibition-exhibitionPlanningInformation");
      fieldSelectorByLabel.put("Exhibition Sections", "csc-exhibition-exhibitionSectionGroup");
      fieldSelectorByLabel.put("Exhibition Status", "csc-exhibition-exhibitionStatusGroup");
      fieldSelectorByLabel.put("Exhibition Title", "csc-exhibition-title");
      fieldSelectorByLabel.put("Exhibition Working Group", "csc-exhibition-workingGroup");
      fieldSelectorByLabel.put("Gallery Rotations", "csc-exhibition-galleryRotationGroup");
      fieldSelectorByLabel.put("General Notes", "csc-exhibition-generalNote");
      fieldSelectorByLabel.put("Location", "csc-exhibition-exhibitionSectionLocation");
      fieldSelectorByLabel.put("Mount?", "csc-exhibition-exhibitionObjectMount");
      fieldSelectorByLabel.put("Name", "csc-exhibition-exhibitionObjectName");
      fieldSelectorByLabel.put("Note", "csc-exhibition-exhibitionObjectNote");
      fieldSelectorByLabel.put("Notes", "csc-exhibition-galleryRotationNote");
      fieldSelectorByLabel.put("Notes", "csc-exhibition-workingGroupNote");
      fieldSelectorByLabel.put("Object", "csc-exhibition-exhibitionObjectNumber");
      fieldSelectorByLabel.put("Object Checklist", "csc-exhibition-exhibitionObjectGroup");
      fieldSelectorByLabel.put("Objects", "csc-exhibition-exhibitionSectionObjects");
      fieldSelectorByLabel.put("Opening Date", "csc-exhibition-venueOpeningDate");
      fieldSelectorByLabel.put("Organizer", "csc-exhibition-organizer");
      fieldSelectorByLabel.put("Person", "csc-exhibition-exhibitionPerson");
      fieldSelectorByLabel.put("Planning Notes", "csc-exhibition-planningNote");
      fieldSelectorByLabel.put("Reference", "csc-exhibition-exhibitionReference");
      fieldSelectorByLabel.put("Reference Note", "csc-exhibition-exhibitionReferenceNote");
      fieldSelectorByLabel.put("Reference Type", "csc-exhibition-exhibitionReferenceType");
      fieldSelectorByLabel.put("Remarks", "csc-exhibition-exhibitionSectionNote");
      fieldSelectorByLabel.put("Remarks", "csc-exhibition-exhibitionStatusNote");
      fieldSelectorByLabel.put("Role", "csc-exhibition-exhibitionPersonRole");
      fieldSelectorByLabel.put("Rotation", "csc-exhibition-exhibitionObjectRotation");
      fieldSelectorByLabel.put("Rotation Name", "csc-exhibition-galleryRotationName");
      fieldSelectorByLabel.put("Section", "csc-exhibition-exhibitionObjectSection");
      fieldSelectorByLabel.put("Section", "csc-exhibition-exhibitionSectionName");
      fieldSelectorByLabel.put("Seq. #", "csc-exhibition-exhibitionObjectSeqNum");
      fieldSelectorByLabel.put("Start Date", "csc-galleryRotationGroup-galleryRotationStartDateGroup");
      fieldSelectorByLabel.put("Status", "csc-exhibition-exhibitionStatus");
      fieldSelectorByLabel.put("Status Date", "csc-exhibition-exhibitionStatusDate");
      fieldSelectorByLabel.put("Venues", "csc-exhibition-venue");
      fieldSelectorByLabel.put("Web Address", "csc-exhibition-venueUrl");
      fieldSelectorByLabel.put("Working Group Title", "csc-exhibition-workingGroupTitle");

      // Entries above with duplicate text labels, to be checked by a human.
      //
      // Some may represent labels for headers above repeatable fields/groups.
      // Duplicate text label: Notes (appears 2 times)
      // Duplicate text label: Remarks (appears 2 times)
      // Duplicate text label: Section (appears 2 times)

      // Messagekeys in the 'uispec' file not matched by text labels
      // in the message bundles file (e.g. 'core-messages.properties').
      //
      // Some of these may be record metadata that is never displayed
      // in the UI. If so, they can be added to the script's stoplist.
      //
      // In other instances, these may represent messagekeys for section
      // headers in the record, rather than for fields.
      //
      // Finally, these may represent sub-records (e.g. Contact in
      // Person and Organization) or other sub-data structures.
      //
      // Not found: text label for message key 'exhibition-organizersLabel'
      // Not found: text label for message key 'exhibition-sponsorsLabel'

      // ----- End of entries generated by an automated script -----


    }
}
