package org.collectionspace.qa.records;

public class Intake extends Record {

    public Intake() {

      // ----- Start of entries generated by an automated script -----
      //
      // (Note: These require review by a human.)
      // (Note: Entries for structured date fields are not yet generated.)

      fieldSelectorByLabel.put("Condition", "csc-intake-conditionInformation");
      fieldSelectorByLabel.put("Condition Check Date", "csc-intake-conditionCheckDate");
      fieldSelectorByLabel.put("Condition Check Note", "csc-intake-conditionCheckNote");
      fieldSelectorByLabel.put("Condition Check Reference Number", "csc-intake-conditionCheckReferenceNumber");
      fieldSelectorByLabel.put("Current Location Note", "csc-intake-currentLocationNote");
      fieldSelectorByLabel.put("Depositor Requirements", "csc-intake-depositorsRequirements");
      fieldSelectorByLabel.put("Entry Date", "csc-intake-entry-date");
      fieldSelectorByLabel.put("Entry Note", "csc-intake-entry-note");
      fieldSelectorByLabel.put("Field Collection Date", "csc-intake-fieldCollectionDate");
      fieldSelectorByLabel.put("Field collection event name", "csc-intake-field-collection-event-name");
      fieldSelectorByLabel.put("Field collection note", "csc-intake-fieldCollectionNote");
      fieldSelectorByLabel.put("Field collection number", "csc-intake-fieldCollectionNumber");
      fieldSelectorByLabel.put("Field collection place", "csc-intake-fieldCollectionPlace");
      fieldSelectorByLabel.put("Insurance", "csc-intake-insuranceInformation");
      fieldSelectorByLabel.put("Insurance Note", "csc-intake-entry-note");
      fieldSelectorByLabel.put("Intake Entry Number", "csc-intake-entry-number");
      fieldSelectorByLabel.put("Location", "csc-intake-locationInformation");
      fieldSelectorByLabel.put("Location Date", "csc-intake-locationDate");
      fieldSelectorByLabel.put("Object Collection Information", "csc-intake-objectCollectionInformation");
      fieldSelectorByLabel.put("Object Entry Information", "csc-intake-objectEntryInformation");
      fieldSelectorByLabel.put("Packing Note", "csc-intake-packing-note");
      fieldSelectorByLabel.put("Policy Number", "csc-intake-insurancePolicyNumber");
      fieldSelectorByLabel.put("Reference Number", "csc-intake-insuranceReferenceNumber");
      fieldSelectorByLabel.put("Reference Number", "csc-intake-valuationReferenceNumber");
      fieldSelectorByLabel.put("Renewal Date", "csc-intake-insuranceRenewalDate");
      fieldSelectorByLabel.put("Return Date", "csc-intake-returnDate");
      fieldSelectorByLabel.put("Valuation", "csc-intake-valuationInformation");
      fieldSelectorByLabel.put("Earliest Entry Date", "csc-intake-entryDateStart");
      fieldSelectorByLabel.put("Earliest Entry Date", "csc-intake-entryDateEnd");
      fieldSelectorByLabel.put("Earliest Return Date", "csc-intake-returnDateStart");
      fieldSelectorByLabel.put("Earliest Return Date", "csc-intake-returnDateEnd");
      fieldSelectorByLabel.put("Record last modified by", "csc-intake-updatedBy");
      fieldSelectorByLabel.put("Earliest Modified Date", "csc-intake-updatedAtStart");
      fieldSelectorByLabel.put("Latest Modified Date", "csc-intake-updatedAtEnd");

      xpathMap.put("Current Owner",             "//*[@id=\"primaryTab\"]/div/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/input[2]");
      xpathMap.put("Depositor"    ,             "//*[@id=\"primaryTab\"]/div/div[3]/div[1]/div[2]/div[1]/div[2]/div[3]/div[2]/table/tbody/tr/td[1]/input[2]");
      xpathMap.put("Field collection source",   "//*[@id=\"primaryTab\"]/div/div[3]/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/ul/li/input[3]");
      xpathMap.put("Field collector",           "//*[@id=\"primaryTab\"]/div/div[3]/div[2]/div[2]/div/div[2]/div[3]/div[2]/div/ul/li/input[3]");
      xpathMap.put("Valuer",                    "//*[@id=\"primaryTab\"]/div/div[3]/div[3]/div[2]/div/div[1]/div/div[2]/input[2]");
      xpathMap.put("Insurer",                   "//*[@id=\"primaryTab\"]/div/div[3]/div[4]/div[2]/div/div[1]/div[1]/div[2]/div/ul/li/input[3]");
      xpathMap.put("Current Location",          "//*[@id=\"repeat::\"]/td[2]/input[2]");
      xpathMap.put("Normal Location",           "//*[@id=\"primaryTab\"]/div/div[3]/div[5]/div[2]/div[2]/div[2]/div/div[2]/input[2]");
      xpathMap.put("Condition Check Assessor",  "//*[@id=\"primaryTab\"]/div/div[3]/div[6]/div[2]/div[1]/div[1]/div[3]/div[2]/div/ul/li/input[3]");
      xpathMap.put("Current Owner Search",      "//*[@id=\"all-content\"]/div/div[1]/div/div/div/div[2]/div[4]/div/div/div/div/div/div[2]/div/ul/li/input[3]");
      xpathMap.put("Depositor Search"    ,                "//*[@id=\"all-content\"]/div/div[1]/div/div/div/div[2]/div[4]/div/div/div/div/div/div[2]/div/ul/li/input[3]");
      xpathMap.put("Current Location  Search",            "//*[@id=\".csc-intake-currentLocationGroup\"]/input[2]");


      dropDownMap.put("Condition Check Method", "csc-intake-conditionCheckMethods");
      dropDownMap.put("Condition Check Reason", "csc-intake-conditionCheckReasons");
      dropDownMap.put("Current Location Fitness", "csc-intake-currentLocationFitness");
      dropDownMap.put("Entry Method", "csc-intake-entryMethod");
      dropDownMap.put("Entry Reason", "csc-intake-entry-reason");
      dropDownMap.put("Field collection method", "csc-intake-fieldCollectionMethods");



      // Entries above with duplicate text labels, to be checked by a human.
      //
      // Some may represent labels for headers above repeatable fields/groups.
      // Duplicate text label: Current Location (appears 2 times)
      // Duplicate text label: Entry Method (appears 2 times)
      // Duplicate text label: Field collection event name (appears 2 times)
      // Duplicate text label: Reference Number (appears 2 times)

      // Messagekeys in the 'uispec' file not matched by text labels
      // in the message bundles file (e.g. 'core-messages.properties').
      //
      // Some of these may be record metadata that is never displayed
      // in the UI. If so, they can be added to the script's stoplist.
      //
      // In other instances, these may represent messagekeys for section
      // headers in the record, rather than for fields.
      //
      // Finally, these may represent sub-records (e.g. Contact in
      // Person and Organization) or other sub-data structures.
      //
      // Not found: text label for message key 'intake-conditionCheckMethodLabel'
      // Not found: text label for message key 'intake-conditionCheckReasonLabel'
      // Not found: text label for message key 'intake-conditionCheckerOrAssessorLabel'
      // Not found: text label for message key 'intake-fieldCollectionMethodLabel'
      // Not found: text label for message key 'intake-fieldCollectionSourceLabel'
      // Not found: text label for message key 'intake-fieldCollectorLabel'
      // Not found: text label for message key 'intake-insurerLabel'

      // ----- End of entries generated by an automated script -----

    }
}
