package org.collectionspace.qa.records;

public class MediaHandling extends Record {

    public MediaHandling() {

    dropDownMap.put("Languages", "csc-media-language");
    dropDownMap.put("Types", "csc-media-type");

    xpathMap.put("Creator",            "//*[@id=\"primaryTab\"]/div/div[3]/div[2]/div[2]/div/div[5]/div/div/div[2]/input[2]");
    xpathMap.put("Publisher",          "//*[@id=\"primaryTab\"]/div/div[3]/div[2]/div[2]/div/div[7]/div/div/div[2]/input[2]");
    xpathMap.put("Rights holder",      "//*[@id=\"primaryTab\"]/div/div[3]/div[2]/div[2]/div/div[9]/div[2]/div/div[2]/input[2]");
    xpathMap.put("Creator Search",     "//*[@id=\"all-content\"]/div/div/div/div/div/div[2]/div[4]/div/div/div/div/div/div[2]/div/ul/li/input[3]");
    xpathMap.put("Publisher Search",   "//*[@id=\"all-content\"]/div/div/div/div/div/div[2]/div[4]/div/div/div/div/div[7]/div[2]/div/ul/li/input[3]");
    xpathMap.put("Rights holder search", "//*[@id=\"all-content\"]/div/div/div/div/div/div[2]/div[4]/div/div/div/div/div[8]/div[2]/div/ul/li/input[3]");

    fieldSelectorByLabel.put("Record last modified by"        ,"csc-media-updatedBy");
    fieldSelectorByLabel.put("Earliest Modified Date"         ,"csc-media-updatedAtStart");
    fieldSelectorByLabel.put("Latest Modified Date"           ,"csc-media-updatedAtEnd");
    fieldSelectorByLabel.put("Dates",                         "csc-dateGroup-date");
    fieldSelectorByLabel.put("Earliest/Single Dates Year",    "csc-structuredDate-dateEarliestSingleYear");
    fieldSelectorByLabel.put("Earliest/Single Dates Month",   "csc-structuredDate-dateEarliestSingleMonth");
    fieldSelectorByLabel.put("Earliest/Single Dates Day",     "csc-structuredDate-dateEarliestSingleDay");
    fieldSelectorByLabel.put("Earliest Dates",                "csc-media-dateStart");
    fieldSelectorByLabel.put("Latest Dates",                  "csc-media-dateEnd");


      // ----- Start of entries generated by an automated script -----
      //
      // (Note: These require review by a human.)
      // (Note: Entries for structured date fields are not yet generated.)

      fieldSelectorByLabel.put("Contributor", "csc-media-contributor");
      fieldSelectorByLabel.put("Copyright statement", "csc-media-copyrightStatement");
      fieldSelectorByLabel.put("Coverage", "csc-media-coverage");
      fieldSelectorByLabel.put("Date", "csc-dimension-valueDate");
      fieldSelectorByLabel.put("Date created", "csc-media-dateCreated");
      fieldSelectorByLabel.put("Date modified", "csc-media-dateModified");
    //   fieldSelectorByLabel.put("Dates", "csc-media-dateGroup");
      fieldSelectorByLabel.put("Description", "csc-media-description");
      fieldSelectorByLabel.put("Dimension", "csc-dimension-dimension");
      fieldSelectorByLabel.put("Dimension", "csc-media-dimension");
      fieldSelectorByLabel.put("Dimension Unit", "csc-dimension-measurementUnit");
      fieldSelectorByLabel.put("Dimensions", "csc-dimension-measuredPartGroup");
      fieldSelectorByLabel.put("External URL", "csc-media-externalUrl");
      fieldSelectorByLabel.put("File Information", "csc-media-fileInformation");
      fieldSelectorByLabel.put("File Information", "csc-media-fileInformationHeader");
      fieldSelectorByLabel.put("File format", "csc-media-format");
      fieldSelectorByLabel.put("File location", "csc-media-location");
      fieldSelectorByLabel.put("File name", "csc-media-filename");
      fieldSelectorByLabel.put("Identification Number", "csc-media-identificationNumber");
      fieldSelectorByLabel.put("Measured By", "csc-dimension-measuredBy");
      fieldSelectorByLabel.put("Measurements", "csc-measuredPartGroup-dimensionSubGroup");
      fieldSelectorByLabel.put("Media Handling Information", "csc-media-mediaInformation");
      fieldSelectorByLabel.put("Method", "csc-dimension-measurementMethod");
      fieldSelectorByLabel.put("Part", "csc-dimension-measuredPart");
      fieldSelectorByLabel.put("Relations", "csc-media-relation");
      fieldSelectorByLabel.put("Source", "csc-media-source");
      fieldSelectorByLabel.put("Subjects", "csc-media-subject");
      fieldSelectorByLabel.put("Summary", "csc-dimension-dimensionSummary");
      fieldSelectorByLabel.put("Thumbnail", "csc-media-imgThumb");
      fieldSelectorByLabel.put("Title", "csc-media-title");
      fieldSelectorByLabel.put("Value", "csc-dimension-value");
      fieldSelectorByLabel.put("Value Qualifier", "csc-dimension-valueQualifier");

      // Entries above with duplicate text labels, to be checked by a human.
      //
      // Some may represent labels for headers above repeatable fields/groups.
      // Duplicate text label: Dimension (appears 2 times)
      // Duplicate text label: File Information (appears 2 times)
      // Duplicate text label: Types (appears 2 times)

      // Messagekeys in the 'uispec' file not matched by text labels
      // in the message bundles file (e.g. 'core-messages.properties').
      //
      // Some of these may be record metadata that is never displayed
      // in the UI. If so, they can be added to the script's stoplist.
      //
      // In other instances, these may represent messagekeys for section
      // headers in the record, rather than for fields.
      //
      // Finally, these may represent sub-records (e.g. Contact in
      // Person and Organization) or other sub-data structures.
      //
      // Not found: text label for message key 'dateGroup-dateLabel'
      // Not found: text label for message key 'dimension-dimensionInformationLabel'
      // Not found: text label for message key 'dimension-dimensionNoteLabel'
      // Not found: text label for message key 'media-blobCsidLabel'
      // Not found: text label for message key 'media-blobsLabel'
      // Not found: text label for message key 'media-externalMediaUrlLabel'
      // Not found: text label for message key 'media-imgOrigLabel'
      // Not found: text label for message key 'media-languagesLabel'
      // Not found: text label for message key 'media-relationsLabel'
      // Not found: text label for message key 'media-sourceUrlLabel'
      // Not found: text label for message key 'media-subjectsLabel'

      // ----- End of entries generated by an automated script -----




    }
}
