package org.collectionspace.qa.records;

public class Work extends Record {

    public Work() {

        requiredMap.put("csc-workAuthority-termDisplayName", "To work, to work we go");

        // ----- Start of entries generated by an automated script -----
        //
        // (Note: These require review by a human.)
        // (Note: Entries for structured date fields are not yet generated.)

        fieldSelectorByLabel.put("Broader Context", "csc-hierarchy-broaderContext");
        fieldSelectorByLabel.put("Broader object type", "csc-hierarchy-broaderContextType");
        fieldSelectorByLabel.put("Creator", "csc-work-creator");
        fieldSelectorByLabel.put("Creator type", "csc-work-creatorType");
        fieldSelectorByLabel.put("Display Name", "csc-workAuthority-termDisplayName");
        fieldSelectorByLabel.put("Equivalent Context", "csc-hierarchy-equivalentContexts");
        fieldSelectorByLabel.put("Formatted Display Name", "csc-workAuthority-termFormattedDisplayName");
        fieldSelectorByLabel.put("History notes", "csc-work-workHistoryNote");
        fieldSelectorByLabel.put("Language", "csc-workAuthority-termLanguage");
        fieldSelectorByLabel.put("Narrower Context", "csc-hierarchy-narrowerContext");
        fieldSelectorByLabel.put("Object component type", "csc-hierarchy-narrowerContextType");
        fieldSelectorByLabel.put("Pref for Lang", "csc-workAuthority-termPrefForLang");
        fieldSelectorByLabel.put("Publisher", "csc-work-publisher");
        fieldSelectorByLabel.put("Publisher type", "csc-work-publisherType");
        fieldSelectorByLabel.put("Qualifier", "csc-workAuthority-termQualifier");
        fieldSelectorByLabel.put("Related Term", "csc-hierarchy-relatedTerms");
        fieldSelectorByLabel.put("Source", "csc-workAuthority-termSource");
        fieldSelectorByLabel.put("Source Detail", "csc-workAuthority-termSourceDetail");
        fieldSelectorByLabel.put("Source Note", "csc-workAuthority-termSourceNote");
        fieldSelectorByLabel.put("Source Unique ID", "csc-workAuthority-termSourceID");
        fieldSelectorByLabel.put("Status", "csc-workAuthority-termStatus");
        fieldSelectorByLabel.put("Term", "csc-workAuthority-termName");
        fieldSelectorByLabel.put("Term Flag", "csc-workAuthority-termFlag");
        fieldSelectorByLabel.put("Term Type", "csc-workAuthority-termType");
        fieldSelectorByLabel.put("Work Information", "csc-work-workAuthorityInformation");
        fieldSelectorByLabel.put("Work Record Type", "csc-work-workType");
        fieldSelectorByLabel.put("Work Term Group(s)", "csc-work-workAuthority");
        fieldSelectorByLabel.put("Work date", "csc-work-workDateGroup");

        // Entries above with duplicate text labels, to be checked by a human.
        //
        // Some may represent labels for headers above repeatable fields/groups.
        // (No duplicate entries generated here by script after removing group entries)

        // Messagekeys in the 'uispec' file not matched by text labels
        // in the message bundles file (e.g. 'core-messages.properties').
        //
        // Some of these may be record metadata that is never displayed
        // in the UI. If so, they can be added to the script's stoplist.
        //
        // In other instances, these may represent messagekeys for section
        // headers in the record, rather than for fields.
        //
        // Finally, these may represent sub-records (e.g. Contact in
        // Person and Organization) or other sub-data structures.
        //
        // Not found: text label for message key 'hierarchy-domaindataLabel'
        // Not found: text label for message key 'hierarchy-equivalentContextLabel'
        // Not found: text label for message key 'hierarchy-equivalentInformationLabel'
        // Not found: text label for message key 'hierarchy-hierarchyInformationLabel'
        // Not found: text label for message key 'hierarchy-narrowerContextsLabel'
        // Not found: text label for message key 'hierarchy-relatedTermLabel'
        // Not found: text label for message key 'workAuthority-termInformationLabel'
        // Not found: text label for message key 'workAuthority-workTermGroupLabel'
        // Not found: text label for message key 'workDateGroup-workDateLabel'

        // ----- End of entries generated by an automated script -----
      
      }
}
